Problem: doctests only work in 1.12
Solution:

 - Make doctests a little bit less restrictive instead of only supporitng 1.13+[1]

References:

[1]: Error in question (difference is highlighted with three asterisk symbols (*))
"""
 1) doctest Uptight.Result.new/1 (1) (UptightTest)
    test/uptight_test.exs:6
    Doctest failed
    doctest:
      iex> Uptight.Result.new(fn () -> :erlang.system_flag(:backtrace_depth, 0); raise "oopsie" end)
      %Uptight.Result.Err{
        err: %Uptight.Trace{
          exception: %RuntimeError{message: "oopsie"},
          stacktrace: [
            {UptightTest, :"-doctest Uptight.Result.new/1 (1)/1-fun-0-", 0,
            [file: '(for doctest at) lib/uptight/result.ex', line: 24]}
          ]
        }
      }
    code:  Uptight.Result.new(fn ->
             :erlang.system_flag(:backtrace_depth, 0)
             raise "oopsie"
           end) === %Uptight.Result.Err{
             err: %Uptight.Trace{
               exception: %RuntimeError{message: "oopsie"},
               stacktrace: [
                 {UptightTest, :"-doctest Uptight.Result.new/1 (1)/1-fun-0-", 0,
                 [file: '(for doctest at) lib/uptight/result.ex', line: 24]}
               ]
             }
           }
    left:  %Uptight.Result.Err{
             err: %Uptight.Trace{
               exception: %RuntimeError{__exception__: true, message: "oopsie"},
               stacktrace: [
                 {
                   UptightTest,
                   :"-doctest Uptight.Result.new/1 (1)/1-fun-0-",
                   0,
                   [{:file, '(for doctest at) lib/uptight/result.ex'}, {:line, 24}, *** {:error_info, %{module: Exception} *** }]
                 }
               ]
             }
           }
    right: %Uptight.Result.Err{
             err: %Uptight.Trace{
               exception: %RuntimeError{__exception__: true, message: "oopsie"},
               stacktrace: [
                 {
                   UptightTest,
                   :"-doctest Uptight.Result.new/1 (1)/1-fun-0-",
                   0,
                   [file: '(for doctest at) lib/uptight/result.ex', line: 24]
                 }
               ]
             }
           }
    stacktrace:
      lib/uptight/result.ex:24: Uptight.Result (module)
"""